# MYSQL CONFIG
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/exam_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:password}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

secret.key=${SECRET_KEY}
app.frontend.url=${FRONTEND_URL:http://localhost:3000}
server.port=${PORT:8080}